version: '3.2'
services:
  app:
    build: ./candidate_code/
    depends_on:
        - 'db'

  db:
    image: postgres
    hostname: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=username
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=database

